### ISSUE TITLE
LowDB v3 support Roadmap

### ISSUE THREAD

**Issue by FossPrime** [lwhiteley/feathers-lowdb#48]
For v1 with LowDB v3 support, the following improvements to [feathers-yaml](https://github.com/FossPrime/feathers-yaml) are needed

- [ ] Custom Model support
- [ ] Default to JSON not Yaml
- [ ] Remove service instantiation function yaml in favor of LowDBService. In @feathersjs/memory it's memory, but this seems like strongly discouraged use, using [MemoryService](https://feathersjs.com/api/databases/memory.html) is preferred. The memory function export is there mostly to slightly ease migration, but it ends up being needlessly confusing, with multiple API's to do the exact same thing.

**Comment by FossPrime** [comment]
@lwhiteley please set default branch to main to improve compatibility and fix a workflow bug. I can get rid of master to reduce confusion.

I have a good feeling about this plugin... The numbers for Yaml on discord and npm were surprisingly good.

**Comment by lwhiteley** [comment]
> please set default branch to main 

done
